name: reverser
services:
  core:
    image: local/reverser-core:0.1
    build:
      context: ./core
  dynamic:
    image: local/reverser-dynamic:0.1
    build:
      context: ./dynamic
      args:
        CORE_IMAGE: local/reverser-core:0.1
  ghidra:
    image: local/reverser-ghidra:0.1
    build:
      context: ./ghidra
      args:
        CORE_IMAGE: local/reverser-core:0.1
  angr:
    image: local/reverser-angr:0.1
    build:
      context: ./angr
      args:
        CORE_IMAGE: local/reverser-core:0.1
